### ISSUE TITLE
Can't add to HA running in VM

### ISSUE THREAD

**Issue by Franzt151** [koying/openrgb_ha#13]
I'm running Windows 10 and running OpenRGB as Admin. I tried connecting HA to my computers SDk Server on the standard port. I believe the issue is somehow related to me running HA in a VM inside unRaid. When I connect, in OpenRGB it lists the connected client IP as my unRaid server not HA. This could be my side too but seems strange. Here is also the log from HA.

`This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/openrgb/config_flow.py:24
Integration: OpenRGB (documentation, issues)
First occurred: 4:43:18 PM (1 occurrences)
Last logged: 4:43:18 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openrgb/network.py", line 137, in read
    self.callback(device_id, packet_type, utils.ControllerData.unpack(data, self._protocol_version))
  File "/usr/local/lib/python3.9/site-packages/openrgb/utils.py", line 547, in unpack
    metadata = MetaData.unpack(data, version)
  File "/usr/local/lib/python3.9/site-packages/openrgb/utils.py", line 489, in unpack
    serial = parse_string(data)
  File "/usr/local/lib/python3.9/site-packages/openrgb/utils.py", line 116, in parse_string
    return parse_var(f'{length}s', data).decode().rstrip('\x00')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 0: invalid start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 198, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 256, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/openrgb/config_flow.py", line 79, in async_step_user
    await asyncio.wait_for(
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openrgb/config_flow.py", line 24, in _try_connect
    conn = OpenRGBClient(_host, _port, name=_client_id)
  File "/usr/local/lib/python3.9/site-packages/openrgb/orgb.py", line 287, in __init__
    self.comms.requestDeviceNum()
  File "/usr/local/lib/python3.9/site-packages/openrgb/network.py", line 188, in requestDeviceNum
    self.read()
  File "/usr/local/lib/python3.9/site-packages/openrgb/network.py", line 116, in read
    self.callback(device_id, packet_type, buff[0])
  File "/usr/local/lib/python3.9/site-packages/openrgb/orgb.py", line 302, in _callback
    self.comms.requestDeviceData(x)
  File "/usr/local/lib/python3.9/site-packages/openrgb/network.py", line 181, in requestDeviceData
    self.read()
  File "/usr/local/lib/python3.9/site-packages/openrgb/network.py", line 139, in read
    raise utils.ControllerParsingError(f"Unable to parse data from request `{packet_type}` for device #{device_id}") from e
openrgb.utils.ControllerParsingError: Unable to parse data from request `1` for device #0
`

**Comment by Franzt151** [comment]
Also I'm running the current version of everything.

**Comment by chrisella** [comment]
I've got the same issue currently with:

OpenRGB 0.6
HA core-2021.11.4
HA supervisor-2021.10.8

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openrgb/network.py", line 137, in read
    self.callback(device_id, packet_type, utils.ControllerData.unpack(data, self._protocol_version))
  File "/usr/local/lib/python3.9/site-packages/openrgb/utils.py", line 547, in unpack
    metadata = MetaData.unpack(data, version)
  File "/usr/local/lib/python3.9/site-packages/openrgb/utils.py", line 489, in unpack
    serial = parse_string(data)
  File "/usr/local/lib/python3.9/site-packages/openrgb/utils.py", line 116, in parse_string
    return parse_var(f'{length}s', data).decode().rstrip('\x00')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 0: invalid start byte
```
