### ISSUE TITLE
Config flow fails to add OpenRGB 0.7 (Stable) on Linux Host, but fine for OpenRGB 0.7 Windows Host

### ISSUE THREAD

**Issue by erwin** [koying/openrgb_ha#20]
# Linux Host:
* OS: Kubuntu 21.10 x86_64
* Kernel: 5.13.0-35-generic

![image](https://user-images.githubusercontent.com/11534217/158518247-89dcecdd-37a3-456c-8827-12dcc71fa29f.png)

The message `Unable to Connect` in the config flow UI seems incomplete, as it is connecting enough that OpenRGB sees the `Client Name: Home Assistant` passed in.

# Windows Host:

Meanwhile, when I choose a windows host in the config flow, it works fine.

![image](https://user-images.githubusercontent.com/11534217/158518526-fc97459a-15f3-42b1-9da6-779318b27604.png)

# Debug Log

Also, to get some helpful debugging in the log, normally this works, but not for openrgb...

```
logger:
  default: warning
  logs:
    custom_components.openrgb: debug
```

**Comment by erwin** [comment]
I still haven't figured out how to get very useful troubleshooting information out of the HA log for the OpenRGB integration...

When I try to add a Linux OpenRGB `Server` I'm getting this in the `home-assistant.log`:

```log
2022-06-16 15:29:52 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _chain_future.<locals>._set_state(<Future pendi...tasks.py:416]>, <Future at 0x...StopIteration>) at /usr/local/lib/python3.9/asyncio/futures.py:378
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 380, in _set_state
    _copy_future_state(other, future)
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 356, in _copy_future_state
    dest.set_exception(_convert_future_exc(exception))
TypeError: StopIteration interacts badly with generators and cannot be raised into a Future
```

Looks like I need to set aside time for the Building a Home Assistant Custom Component 4 part tutorial to better understand how to debug this.

Apparently the `dev container` stuff also will avoid 1-2 minute HA restarts.

https://aarongodfrey.dev/home%20automation/building_a_home_assistant_custom_component_part_1/

https://community.home-assistant.io/t/tutorial-for-creating-a-custom-component/204793/17

https://developers.home-assistant.io/docs/creating_component_index/

https://github.com/home-assistant/example-custom-config/tree/master/custom_components/

**Comment by felipecrs** [comment]
@erwin, can you test with latest versions and close the issue if this is fixed?
